name: "ZeroThreat AI Pentest"
description: "Find and validate real exploitable vulnerabilities in web apps and APIs."
branding:
  icon: check-circle
  color: purple
inputs:
  ZT_TOKEN:
    description: 'ZT_TOKEN to authenticate API request & start the scan.'
    required: true
  #Wait for analysis settings
  WAIT_FOR_ANALYSIS:
    description: 'Set this true to wait for analysis to complete before finishing job.'
    required: false
    default: false
  ON_PREM_PROXY_API_URL:
    description: 'Set proxy url host to scan internal targets.'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
